### ISSUE TITLE
Add session-regression materials

### ISSUE THREAD

**Issue by olgadet** [NBISweden/workshop-biostatistics#10]

**Comment by winni2k** [comment]
I see we have some example data for session-regression-I. Does this dataset also have a second continuous and a factor variable that we could use for the regression-II?

**Comment by winni2k** [comment]
I've had a look at dataset repositories inside R and [here](http://users.stat.ufl.edu/~winner/datasets.html), but I could not find a biomedical-inspired dataset that had the following requirements:

1. At least four columns
2. A continuous response variable
3. Two continuous predictor variables
4. At least one categorical predictor variable

**Comment by olgadet** [comment]
Aaaa...I've missed this conversation, too many Github notifications. Sorry! We can find a better dataset for next time!
